### ISSUE TITLE
Imgui asserts in release mode

### ISSUE THREAD

**Issue by emoon** [emoon/ProDBG#179]
Repro step (Mac)

1. ``scripts/mac_build_release.sh``
2. ``t2-output/macosx-clang-release-default/ProDBG.app/Contents/MacOS/prodbg``
3. Right click in the empty window.
4. Notice this assert ``Assertion failed: (g.CurrentWindowStack.Size == 1), function EndFrame, file /<path>/prodbg/src/native/external/imgui/imgui.cpp, line 2413.``

**Comment by kondrak** [comment]
Windows release build doesn't seem to be affected by this.

**Comment by emoon** [comment]
It's kinda weird it only happens on Mac :)

**Comment by darthdeus** [comment]
I know I'm over a year late, but just ran into this with .NET bindings to ImGui on Mac, and this is literally the only google result with the assert error. Your commit says

   return integers instead of bools not to confuse the compiler

could you explain why/how does it confuse the compiler? I'm a bit confused as to what causes this error.

**Comment by emoon** [comment]
Trying to remember what the cause of this was. Maybe @kondrak remembers? I know we talked about this specific issue.

**Comment by kondrak** [comment]
Ah yes, this was a weird one and it took me a while to get down to what the problem was.
Here the problem was conversion from bool -> int in the FFI. In several instances the value 'true' was converted to 0 on return (either due to compiler opts or possibly UB somewhere along the way), so the safest way to go was to explicitly use integers. I wasn't 100% convinced we were not dealing with some sort of undefined behavior here, so using ints felt like the most stable solution to the problem.

**Comment by kondrak** [comment]
Also noteworthy - only compiling release builds on OSX had this issue, Linux and Windows builds worked fine, so this was either a coincidence and we did in fact dealt with UB all the time or the build tools on Mac are still flawed (though I'd find that unlikely).

**Comment by emoon** [comment]
Ah yes. I think in general you may run into this problem (unrelated to the issue here) if you haven't "poped" some window/control (or something similar) Like you have a `BeginWindow` but never call `EndWindow` I can't remember the exact function names as I don't use ImGui right now but that is the gist of it at least.

**Comment by kondrak** [comment]
Right, that was in fact what I suspected was happening here at first but seeing how the stack was supposingly empty after calling `BeginWindow` was what caught my attention. I can't remember where exactly in the imgui code the conversion was problematic but in the end it resulted in the assert.
