### ISSUE TITLE
Resizing doesn't work correctly sometimes

### ISSUE THREAD

**Issue by emoon** [emoon/ProDBG#182]
Repro steps:

1. Create a layout so it looks like this

![resize_bug](https://cloud.githubusercontent.com/assets/350822/16177725/5eae36f0-3635-11e6-881d-49a6c38670a0.png)

2. Drag the marked slider up/down and notice that plugin 2 bar is also moving up/down which it shouldn't

Notice that this behavior is not consistent and work sometimes and sometimes not.

**Comment by SlNPacifist** [comment]
This happens due to Viewdock structure: it only allows splits in two parts. In this case structure is as follows: (50% Plugin 0) / (50 % (50% Plugin 1 / 50% Plugin 2)). When you move first slider, you decrease size of Plugin 0 and increase size for both Plugin 1 and Plugin 2. That is the reason for border between Plugin 1 and Plugin 2 to move.

**Comment by emoon** [comment]
@SlNPacifist Ah yes that actually make sense. Do you think you can do that as part of your restructuring of the data layout?

**Comment by SlNPacifist** [comment]
I'll think about it today. It seems to simplify some things in data structure but I could be wrong.

**Comment by emoon** [comment]
Alright. Sounds good.
