### ISSUE TITLE
Add floating support for docks

### ISSUE THREAD

**Issue by emoon** [emoon/ProDBG#183]
It should be possible to "detach" a view from the docking and making it possible. It would likely be best to have viewdock keeping track of floating docks also.

**Comment by SlNPacifist** [comment]
Right now different views z-indexes are controlled by Imgui. When view is clicked, it floats up. If viewdock's (background) view is clicked, it could cover floating window completely. Since background views cannot be moved, floating windows will be buried forever. Is there a way to say Imgui "This view should always be higher then these views"? Or something like this to prevent "burying" floating windows.

**Comment by emoon** [comment]
Good question. I will have to ask.

**Comment by emoon** [comment]
Something else that needs to be fixed for adding floating support is not to have this hard coded https://github.com/emoon/ProDBG/blob/master/src/native/ui/imgui_ffi.cpp#L1588 (as it doesn't allow floating right now)

**Comment by emoon** [comment]
@SlNPacifist See reply in linked issue. Will that work you think?

**Comment by SlNPacifist** [comment]
Checking...

**Comment by emoon** [comment]
Sounds good.

**Comment by SlNPacifist** [comment]
How will floating windows be used? With current viewdock float will always be hiding something behind it I can't see when this will be useful. The only use I can think of is to make something float to restructure workspace.

**Comment by emoon** [comment]
Now when I think about it this is likely not needed. Dragging between workspaces or within the workspace should only be a rectangle overlay or something like so lets cut this feature.

**Comment by emoon** [comment]
So I will just close this one.
