### ISSUE TITLE
Readme.md

### ISSUE THREAD

**Issue by clankill3r** [emoon/ProDBG#338]
Hey emoon,

not really an issue. But I saw an image of your debugger on the IMGUI github page.
(https://github.com/ocornut/imgui/issues/123#issuecomment-94067137).
Which lead me to here.

I think you should drop an image in your Readme.md as well. Cause it looks really nice what you are working on.

best Doeke

**Comment by emoon** [comment]
Hi,

I'm sorry to say I have switch to Qt from imgui so that info is actually incorrect now.

**Comment by clankill3r** [comment]
Can I know what your reason was to switch to Qt?

**Comment by emoon** [comment]
Primary text.

* Supporting different fonts for different langs becomes a bit of headace after a while (esp with Arabic/Japanese non-latin based langs in general.

* Keyboard bindings (not supported, may have improved since I switched)

* Lack of documentation (not a major issue but Qt's documentation is world class)

* Serialization. This is all handled for you in Qt. You can do it yourself in imgui apps but is manual. 

* Some more things also that I don't remember right now.

There are some more writings over here https://github.com/emoon/ProDBG/issues/327 and also this post here lists some good reasons for using Qt

**Comment by emoon** [comment]
Will close this one now. Feel free to add more comments if you wish.
